ALTER TYPE "Grade" ADD VALUE IF NOT EXISTS 'PE1';
ALTER TYPE "Grade" ADD VALUE IF NOT EXISTS 'PE2';
ALTER TYPE "Grade" ADD VALUE IF NOT EXISTS 'PE3';
ALTER TYPE "Grade" ADD VALUE IF NOT EXISTS 'PC1';
ALTER TYPE "Grade" ADD VALUE IF NOT EXISTS 'PC2';